version: '3'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres-14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/data/postgres

  sales-api:
    image: sales-api
    container_name: sales-api
    build:
      context: .
    volumes:
      - .:/src/app
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always

  redis:
    image: redis:6.0
    container_name: redis-server
    ports:
      - '6379:6379'

volumes:
  postgres-data:

networks:
  app-nest-network:
    external: true
