export const products = [
  {
    name: 'Notebook Samsung KB-366',
    price: 2500,
    inventory: 5,
    description: 'Notebook Samsung KB-366 descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'Smartphone Tech X9',
    price: 800,
    inventory: 10,
    description: 'Smartphone Tech X9 descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'Wireless Headphones Pro',
    price: 150,
    inventory: 20,
    description: 'Wireless Headphones Pro descrever características do produto',
    category: 'Eletrônicos',
  },
  {
    name: 'Tablet Nexus S10',
    price: 1200,
    inventory: 8,
    description: 'Tablet Nexus S10 descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'Gaming Laptop TitanX',
    price: 3500,
    inventory: 3,
    description: 'Gaming Laptop TitanX descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'VR Headset VRX-500',
    price: 300,
    inventory: 15,
    description: 'VR Headset VRX-500 descrever características do produto',
    category: 'Eletrônicos',
  },
  {
    name: 'Smart TV Quantum Q90',
    price: 2000,
    inventory: 6,
    description: 'Smart TV Quantum Q90 descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'Bluetooth Speaker Pulse',
    price: 70,
    inventory: 25,
    description: 'Bluetooth Speaker Pulse descrever características do produto',
    category: 'Eletrônicos',
  },
  {
    name: 'Camera ProShot Z7',
    price: 1000,
    inventory: 12,
    description: 'Camera ProShot Z7 descrever características do produto',
    category: 'Fotografia',
  },
  {
    name: 'Gaming Console XGame 9000',
    price: 450,
    inventory: 18,
    description:
      'Gaming Console XGame 9000 descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'Wireless Mouse Stealth M6',
    price: 40,
    inventory: 30,
    description:
      'Wireless Mouse Stealth M6 descrever características do produto',
    category: 'Acessórios de Computador',
  },
  {
    name: 'Laptop Stand ErgoMax',
    price: 50,
    inventory: 40,
    description: 'Laptop Stand ErgoMax descrever características do produto',
    category: 'Acessórios de Computador',
  },
  {
    name: 'Smart Watch WristPulse',
    price: 180,
    inventory: 22,
    description: 'Smart Watch WristPulse descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'Monitor UltraView 27"',
    price: 300,
    inventory: 9,
    description: 'Monitor UltraView 27" descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'External SSD FlashJet 500GB',
    price: 120,
    inventory: 35,
    description:
      'External SSD FlashJet 500GB descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'Printer InkJet Pro 2000',
    price: 80,
    inventory: 14,
    description: 'Printer InkJet Pro 2000 descrever características do produto',
    category: 'Tecnologia',
  },
  {
    name: 'Wi-Fi Router SpeedMaster X5',
    price: 90,
    inventory: 28,
    description:
      'Wi-Fi Router SpeedMaster X5 descrever características do produto',
    category: 'Redes',
  },
  {
    name: 'Wireless Keyboard KeyWave',
    price: 60,
    inventory: 33,
    description:
      'Wireless Keyboard KeyWave descrever características do produto',
    category: 'Acessórios de Computador',
  },
  {
    name: 'Noise-Canceling Earbuds ZenPod',
    price: 100,
    inventory: 17,
    description:
      'Noise-Canceling Earbuds ZenPod descrever características do produto',
    category: 'Eletrônicos',
  },
  {
    name: 'Action Camera XtremeCam',
    price: 150,
    inventory: 23,
    description: 'Action Camera XtremeCam descrever características do produto',
    category: 'Fotografia',
  },
];
